var RESOURCE = 0,
DEVCARD = 1,
BUILDING = 2;

var RESOURCE_DESERT = 0,
RESOURCE_LUMBER	= 1,
RESOURCE_BRICK		= 2,
RESOURCE_SHEEP		= 3,
RESOURCE_GRAIN		= 4,
RESOURCE_ORE		= 5;

var BUILDING_ROAD = 0,
BUILDING_SETTLEMENT = 1,
BUILDING_CITY = 2;