var RESOURCE = 0,
DEVCARD = 1,
BUILDING = 2;

var RESOURCE_DESERT = 0,
RESOURCE_LUMBER	= 1,
RESOURCE_BRICK		= 2,
RESOURCE_SHEEP		= 3,
RESOURCE_GRAIN		= 4,
RESOURCE_ORE		= 5;
NUM_RESOURCES = RESOURCE_ORE + 1;

var BUILDING_ROAD = 0,
BUILDING_SETTLEMENT = 1,
BUILDING_CITY = 2;

var CORNER_TL = 0,
CORNER_TR = 1,
CORNER_R = 2,
CORNER_BR = 3,
CORNER_BL = 4,
CORNER_L = 5;

var EDGE_T = 0,
EDGE_TR = 1,
EDGE_BR = 2,
EDGE_B = 3,
EDGE_BL = 4,
EDGE_TL = 5;